CREATE TABLE "ATG_4543_TIMCRD_SHFT" (
 "CHARGE_DATE" DATE,
 "EMPLOYEE" CHAR(5),
 "WORK_ORDER" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQUENCE" CHAR(6),
 "WORKCENTER" CHAR(4),
 "HOURS" DOUBLE,
 "SHIFT" INTEGER,
 "OVERRIDE" CHAR(2) );